require: rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
Layout/LineLength:
  Max: 200
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/RescueEnsureAlignment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  Enabled: false
Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/AccessModifierDeclarations:
  EnforcedStyle: inline
Style/AccessorGrouping:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/FormatStringToken:
  EnforcedStyle: template
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: hash_rockets
Style/MultipleComparison:
  Enabled: false
Style/RegexpLiteral:
  EnforcedStyle: percent_r
Style/SafeNavigation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/YodaCondition:
  Enabled: false
